name: Fetch, build and deploy docs

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch branch
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: make install_docs

      - name: Build docs
        run: make create_docs

      - name: Create the CNAME for GitHub Pages
        run: echo discordhttp.alexflipnote.dev > ./docs/_build/html/CNAME

      - name: Prevent GitHub Pages Jekyll behaviour
        run: touch ./docs/_build/html/.nojekyll

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./docs/_build/html
          clean: true
